services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: rust_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      RUST_LOG: info

  db:
    image: postgres:16
    container_name: rust_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rust_db
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata_prod:
